.PHONY: all progs run clean submit

TRACE=--trace
VFILES=$(wildcard *.sv)
CFILES=$(wildcard *.cpp)

VTOP_COMMAND_LINE=

all: obj_dir/Vtop

obj_dir/Vtop: obj_dir/Vtop.mk
	$(MAKE) -j2 -C obj_dir/ -f Vtop.mk CXX="clang++"

obj_dir/Vtop.mk: $(VFILES) $(CFILES) 
	verilator -Wall -Wno-LITENDIAN -Wno-lint -O3 $(TRACE) --no-skip-identical --cc top.sv \
	--exe $(CFILES) --top-module top

run: obj_dir/Vtop
	cd obj_dir/ && ./Vtop $(VTOP_COMMAND_LINE)

clean:
	rm -rf obj_dir/ trace.vcd core

